### ISSUE TITLE
services fail on restart of container

### ISSUE THREAD

**Issue by orodbhen** [adelton/docker-freeipa#10]
After creating the initial container named "ipa-server", I stopped and and started it with

    docker start -ia ipa-server

Everything started up without errors, and I was able to add users and authenticate over LDAP. 

Unfortunately, when I stopped and started it again, some services failed to start:

    FreeIPA server is already configured, starting the services.
    Starting [ntpd.service]
    Starting [certmonger.service]
    Starting [ipa.service]
    Existing service file detected!
    Assuming stale, cleaning and proceeding
    Starting Directory Service
    Failed to data from service file: Failed to get list of services to probe status:
    Directory Server is stopped
    Shutting down
    Starting [sssd.service]
    ^C[admin@airbuildserver openldap]$ docker start -ai ipa-server 
    FreeIPA server is already configured, starting the services.
    Starting [ntpd.service]
    Starting [certmonger.service]
    Starting [ipa.service]
    Existing service file detected!
    Assuming stale, cleaning and proceeding
    Starting Directory Service
    Failed to data from service file: Failed to get list of services to probe status:
    Directory Server is stopped
    Shutting down
    Starting [sssd.service]

Also, if I commit the container, and then run it again to make changes, e.g. change port mapping, it starts certmonger and ntp, and then crashes.

**Comment by adelton** [comment]
> Starting Directory Service
> Failed to data from service file: Failed to get list of services to probe status: Directory Server is stopped

Is there anything of interest in the log files?

When you try to start the directory service manually at that point, will it run?

> it starts certmonger and ntp, and then crashes. 

Is that the same crash?

**Comment by orodbhen** [comment]
I erased the image and containers, so I can't check the logs. 

> Is that the same crash?

No. In that case it only shows those services start, and then the container stops. 

I have a CentOS 7 image with full systemd running very well inside of it, so I may try installing IPA there. I've already created several other images and containers from it running various services. It doesn't seem like IPA likes having it's IP address change, though, and I'm not sure how to resolve that.

**Comment by adelton** [comment]
> It doesn't seem like IPA likes having it's IP address change, though, and I'm not sure how to resolve that.

We call the ```update_server_ip_address``` to set the IP address either to the local IP address of the container (useful if you only want the IPA server accessible on the same host), or to one provided via the ```IPA_SERVER_IP```, in which case you can give it the IP address of the host.

**Comment by tkent-xetus** [comment]
I also ran into this issue and came across this thread. I'm only seeing the commit/relaunch problem, but I suspect I would run into the IP address problem given more restarts.

I'm very interested in what the solution will be, since the impact of this issue is that backups of a freeipa container can't be relied on and we can't setup our master image on a local system, test it out, then deploy it.


After doing some debugging I've come up with a work around that has proven reliable, at least in my case. In case it's helpful, I'll include the work around here.

_(Full disclaimer: I'm new to docker and just started porting our company's apps over recently. There may be some obvious reason why my work around is the wrong thing to do.)_

When I looked into the commit/relaunch scenario, I found that all the services that failed to start up failed to do so (directly or indirectly) because of a socket connection connection issue. In every case, a socket file was left in the image file system and removing it then restarting the service resolved the issue. The short version of the work around is:

1. Remove the problematic socket files
2. Commit a version of the container without the socket files
3. Use the new image

The socket files to remove are:
```
/var/run/dbus/system_bus_socket
/var/run/ipa_memcached/ipa_memcached
/var/run/slapd-XETUS-COM.socket
/var/lib/sss/pipes/private/sbus-monitor
```

**Comment by adelton** [comment]
Can you please try the latest code? It separates the configuration / data into a volume, making it much easier to backup just the relevant bits, as well as upgrading to newer versions.

**Comment by tkent-xetus** [comment]
Separating the configuration/data from the container is a great solution, much better than needing to rely on container snapshots. I've been using the latest code for a week now and it works great.

IMO this issue is now moot with the new functionality.

**Comment by adelton** [comment]
Thank you for the testing you gave to the new code.

I'm going to close this issue now -- feel free to reopen or open a new one if you see a problem with service start.
