### ISSUE TITLE
DNS and network configuration in production

### ISSUE THREAD

**Issue by roderickm** [adelton/docker-freeipa#17]
What is the recommended way to structure the docker network and IP addresses to use FreeIPA with DNS enabled?

When all relevant ports are forwarded from the host, the container answers DNS queries with its internal docker-assigned address (172.17.0.39, for instance). The SRV records for Kerberos and LDAP point clients to an address they cannot reach instead of the host's address where the services are exposed. FreeIPA is unaware that docker exposes its services to a different network as a different address.

When the container is instead run with `--net=host` to take on the hosts' network stack and address, the container's installation script has a conflict with host's systemctl d-bus: 
> CalledProcessError: Command '/bin/systemctl start messagebus.service' returned non-zero exit status 10

Is there a better way to approach this that better supports a containerized FreeIPA with DNS? Thanks!

**Comment by adelton** [comment]
Run the container with ```-e IPA_SERVER_IP=<the-host-ip>```. That will cause the IP address that IPA server stores about itself in the DNS to be updated to that value.

From within the container, we don't have a way to reliably figure out the IP address of the host or values used with the ```-p``` options. That's why we went with being explicit.

Let me know if this helps.

I will look at the ```--net=host``` use case.

**Comment by roderickm** [comment]
Thank you, that works here. I had tried setting `IPA_SERVER_IP` earlier but was misled by the messages on the first run of the container which said, 
> Using reverse zone 0.17.172.in-addr.arpa.
>
>The IPA Master Server will be configured with:
>Hostname:      ipa1.example.net
>IP address:    172.17.0.7
>Domain name:   example.net
>Realm name:    EXAMPLE.NET

This time I pressed forward despite the messages and now see that service discovery works as expected on the `IPA_SERVER_IP`. The initial reverse zone is configured for the private docker network `0.17.172.in-addr.arpa`, but it's possible to add a reverse zone for the host's address space alongside that.

The `--net=host` may be a beneficial use case for someone else, but I was only considering it as a possible alternative to coerce the container to use the host's IP address. Thanks again for the quick response, and for this helpful project.

**Comment by adelton** [comment]
Thanks for reporting the success.

The problem with the initial IP address and reverse zone will hopefully be addressed by https://fedorahosted.org/freeipa/ticket/2715. Since ```ipa-server-install``` is way to eager to test the IP address and whether it is one of its local addresses instead of testing that the IP address is routed toward IPA server but not necessarily its local address.

You should be able to pass parameter to avoid setting up the ```0.17.172.in-addr.arpa.``` zone to avoid polluting your DNS.

**Comment by adelton** [comment]
> The --net=host may be a beneficial use case for someone else, but I was only considering it as a possible alternative to coerce the container to use the host's IP address. Thanks again for the quick response, and for this helpful project.

For the record, I've now tried the ```centos-7-upstream``` branch and ``--net=host``` on RHEL 7 host and I did not see any D-Bus related errors.
