### ISSUE TITLE
can not connect to the freeipa web ui using the host IP

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#26]
Hello,

Could you please give me an example on how to run the freeipa so that the freeipa web ui is available on the local host and on external hosts ? 

Is-it possible mapping the 80 and 443 freeipa ports to different ports on the host ? 

Thanks a lot
Karl Forner

**Comment by adelton** [comment]
Just run `docker run` with `-p 80:80 -p 443:443`.

Remapping the ports is possible from docker point of view with `-p hostportfor80:80 -p hostportfor443:443` but note that it will likely not do what you expect -- both the WebUI itself and the admin/client tools expect the service to be run on port 443. Therefore, better approach might be to use different IP address (alias on the host) and bind the ports to it.

If it's more than WebUI that you want accessible by external hosts, check the README for the full list of ports that you probably want to bind, as well as the part about `IPA_SERVER_IP` -- you might want it set up so that the DNS record of the IPA server itself is updated to point to the external IP address.

**Comment by kforner** [comment]
Hi, thanks for your quick reply.
What I want to achieve: pretend that the docker host is the freeipa server, and offer all services.
The problem is that I already have a web server on port 80 and 443. 
I tried as you suggested to forward on other ports, but it seems that the web ui redirects URLs on fixed ports. 

My current plan is to mess up with **/data/etc/httpd/conf.d/ipa-rewrite.conf**, does it seem right to you ?
```
# VERSION 6 - DO NOT REMOVE THIS LINE

RewriteEngine on

# By default forward all requests to /ipa. If you don't want IPA
# to be the default on your web server comment this line out.
RewriteRule ^/$ https://ipa.example.test/ipa/ui [L,NC,R=301]

# Redirect to the fully-qualified hostname. Not redirecting to secure
# port so configuration files can be retrieved without requiring SSL.
RewriteCond %{HTTP_HOST}    !^ipa.example.test$ [NC]
RewriteRule ^/ipa/(.*)      http://ipa.example.test/ipa/$1 [L,R=301]

# Redirect to the secure port if not displaying an error or retrieving
# configuration.
RewriteCond %{SERVER_PORT}  !^443$
RewriteCond %{REQUEST_URI}  !^/ipa/(errors|config|crl)
RewriteCond %{REQUEST_URI}  !^/ipa/[^\?]+(\.js|\.css|\.png|\.gif|\.ico|\.woff|\.svg|\.ttf|\.eot)$
RewriteRule ^/ipa/(.*)      https://ipa.example.test/ipa/$1 [L,R=301,NC]

# Rewrite for plugin index, make it like it's a static file
RewriteRule ^/ipa/ui/js/freeipa/plugins.js$    /ipa/wsgi/plugins.py [PT]

```

**Comment by adelton** [comment]
> I tried as you suggested to forward on other ports, but it seems that the web ui redirects URLs on fixed ports.

Yes. You are hitting https://github.com/adelton/docker-freeipa/issues/18 and https://fedorahosted.org/freeipa/ticket/3955. It's a generic FreeIPA issue, certainly amplified in the container setup because containers make it much easier to install multiple different services on the host, making more services competing for the ports. But as a generic IPA issue it really needs to be resolved there. If you get Apache configuration which will make the co-existence with other application easy / possible, I'm sure freeipa-devel folks will love to hear about it either on that mailing list or in the above mentioned ticket.

If you are looking for fast way to set things up, going with the additional IP address on the host will likely be smoother / faster sailing.

**Comment by kforner** [comment]
>If you are looking for fast way to set things up, going with the additional IP address on the host will likely >be smoother / faster sailing.

Could you please give me some additional info about how do it ? 
Do I need to obtain an additional from the network administrators for my host ?
Thanks

**Comment by adelton** [comment]
> Do I need to obtain an additional from the network administrators for my host ?

Yes.

**Comment by mefisto74** [comment]
i cant browse to free ipa web ui even with -p 80:80 -p 443:443  options. 
im using podman on gentoo host. when i type in browser http://hostip id redirect me to ipa.domainame.net (which i configured) and give me timeout error.
then i added dns of free ipa server (host ip) to my resolv.conf and after that i every time get timeout error

runned container with command


`podman run -ti --rm --name ipademo --network newnet -e IPA_SERVER_IP=10.89.0.5 -h ipa.domainname.net -p 53:53/udp -p 53:53  -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464  -p 88:88/udp -p 464:464/udp -p 123:123/udp --read-only -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/lib/ipa-data:/data:Z 80a03108145b ipa-server-install  --skip-mem-check`

newnet.conflist : 

```
   "cniVersion": "0.4.0",
   "name": "newnet",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "hairpinMode": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.0.0/24",
                      "rangeStart": "10.89.0.5",
                      "rangeEnd": "10.89.0.5",
                     "gateway": "10.89.0.1"
                  }
               ]
            ]
         },
         "capabilities": {
            "ips": true
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "tuning"
      }
   ]
}
```




tried cenos8 stream image and rocky. problem the same. what am i doing wrong?

**Comment by rcritten** [comment]
The port forward works if your client is being redirected. You can confirm using curl instead: curl http://hostip

I'd suggest using dig to check the DNS resolution.

**Comment by m3fist0** [comment]
i still cant browse to freipa webui. i think the problem is that i use standart bridge network that have network 10.89.0.0/16 but my standart network is 192.168.6.0/24
and when i follow hots ip it redirects me to ipa.domain.net... that have ip from 10.89.0.0/16 network.

 i cant find setting to resolving webui to 192.168.6.0/24 network . i tried option -e IPA_SERVER_IP from 192.168.6.0/24 network but looks like nothing happened.

tried used macvlan network from podman, ip set was successfull but my network cant see this container (no ping no reaction)

tried use bridge with ip from (192.168.6.0/24) network same problem
ipactls status saying all services  running
i have no idea what i doing wrong, in manuals people say just forward ports and it should work... please help

**Comment by mefisto74** [comment]
i still cant browse to freipa webui. i think the problem is that i use standart bridge network that have network 10.89.0.0/16 but my standart network is 192.168.6.0/24
and when i follow hots ip it redirects me to ipa.domain.net... that have ip from 10.89.0.0/16 network.

i cant find setting to resolving webui to 192.168.6.0/24 network . i tried option -e IPA_SERVER_IP from 192.168.6.0/24 network but looks like nothing happened.

tried used macvlan network from podman, ip set was successfull but my network cant see this container (no ping no reaction)

tried use bridge with ip from (192.168.6.0/24) network same problem
ipactls status saying all services running
i have no idea what i doing wrong, in manuals people say just forward ports and it should work... please help

**Comment by adelton** [comment]
Start by filing separate issue, do not try to revive seven year old issue that was about different problem.

Then be very precise with the information you provide -- for example you say "when i follow hots ip it redirects me to ipa.domain.net" but it is not clear how you "follow" (is that via curl? show the exact command), and if there is something weird, try to explain why it is weirdly behaving (why would the redirect go to `ipa.domain.net` when the hostname used is `ipa.domainname.net` -- is that a typo?)
