### ISSUE TITLE
ntp server ?

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#27]
Hi,

Is there a ntp server supposed to run inside the freeipa server container ? 
I bound the port using "-p 123:123/udp" but it does not seem to work:

- from the docker host: 
```
ntpdate localhost
 2 Jul 15:45:28 ntpdate[1461]: bind() fails: Permission denied

ntpdate $container)ip
 2 Jul 15:45:37 ntpdate[1472]: bind() fails: Permission denied
``` 
- from inside the container:
```
ps -fA | grep ntp
=> nothing

ntpdate localhost
 2 Jul 09:47:22 ntpdate[623]: no server suitable for synchronization found
```

Is there something wrong ?

Best,
Karl

**Comment by adelton** [comment]
You need to use `--cap-add=SYS_TIME` when running the server container or `ntpd` will fail.

Even if you do that, SELinux will likely (depending on your distribution and docker daemon options) prevent `ntpd` doing its job but at least it will stay around so that the client can connect to it.

I'd really recommend running `ntpd`/`chronyd` either on the host directly or in separate container.

**Comment by kforner** [comment]
>I'd really recommend running ntpd/chronyd either on the host directly or in separate container.

ok, that was also my conclusion. So if I understand correctly the actual purpose of "-p 123:123/udp" in the docker run command is not to share the ntp service from the container to the host, but the opposite ?

Many thanks.

**Comment by adelton** [comment]
> So if I understand correctly the actual purpose of "-p 123:123/udp" in the docker run command is not to share the ntp service from the container to the host, but the opposite ?

Well, the goal was to show how to make all the ports from the container accessible on the host, for general case. So that people who want to have the NTP server in that IPA container and it happens to work there for them are not surprised that it's not accessible from outside.

In general, on every host you typically just want one NTP server running anyway, so the planning is on the person deploying the containers to decide if they want another NTP server at all.

**Comment by kforner** [comment]
So suppose you run the ntp server on the host. How do synchronize the clocks between the docker and the host ? By using  -v /etc/localtime:/etc/localtime:ro ?

**Comment by adelton** [comment]
There isn't different time between the host and the docker containers -- the docker container is merely set of processes running on the host itself, so they use the hardware clock of the host anyway.

The `/etc/localtime` specifies the time zone, it does not assure clock accuracy.

**Comment by kforner** [comment]
Ok, perfect. So basically there's nothing to do. I was wondering due to the freeipa-client issue I just submitted.
