### ISSUE TITLE
must disable DNS client to create the freeIPA container instance. 

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#30]
In my setup, the DNS server running in the docker container is bound to the docker host throught port forwarding (-p). 
So the docker host "is" the DNS server, and as such is client of itself (i.e. is in the /etc/resolv.conf).
So far so good, but in this setup, before creating the freeipa container instance, it seems that I must first disable the (local) DNS nameserver in  /etc/resolv.conf, run the freeipa container, then reenable the DNS in /etc/resolv.conf, otherwise I get errors:
```
Warning: skipping DNS resolution of host ipa.quartzbio.com
The domain name has been determined based on the host name.

Checking forwarders, please wait ...
ipa         : ERROR    Forwarder 10.9.70.3 does not work
Forwarder 10.9.70.3 does not respond
FreeIPA server configuration failed.
```
where 10.9.70.3 is the IP address of the docker host

My question: is there a way to be able to start the freeipa without having to mess with the host setup ?

Regards, and many thanks for the docker !!

P.S
current docker run command (I tried many variants):
```
eval "PASSWORD_VALUE=\${IPA_PASSWORD}" && \
	docker run --name freeipa -t -d \
	-e IPA_SERVER_IP=10.9.70.3 \
	-e IPA_SERVER_INSTALL_OPTS="--no-host-dns --forwarder=8.8.8.8 -N" \
	-h ipa.quartzbio.com \
	-e PASSWORD=$PASSWORD_VALUE \
	-v /secure/freeipa_server/freeipa/data:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-p 53:53  -p 53:53/udp \
	-p 9980:80 -p 9943:443 \
	-p 389:389 -p 636:636 -p 88:88 -p 464:464 \
	-p 88:88/udp -p 464:464/udp -p 7389:7389 \
	-p 9443:9443 -p 9444:9444 -p 9445:9445  adelton/freeipa-server
```

**Comment by adelton** [comment]
That DNS server -- is that run on the same host in different container, or is that DNS server that you plan to setup as part of the FreeIPA container?

**Comment by adelton** [comment]
Also, you say:

> before creating the freeipa container instance, it seems that I must first disable the (local) DNS nameserver in /etc/resolv.conf

That local DNS nameserver -- which one is it? Another DNS server running on the host itself (outside of containers)?

If would help if you showed the content of /etc/resolv.conf on the host, the IP address of the host, the IP address of the FreeIPA container, and the IP address of the other DNS server container, if there is any.

**Comment by karl-forner-quartz-bio** [comment]
docker host ip: 10.9.70.3
**/etc/resolv.conf** (N.B: localhost 10.9.70.3 disabled to be able to run the container)
```
#nameserver 10.9.70.3
nameserver 212.121.128.10
nameserver 212.121.128.11
```
the local DNS nameserver runs in the freeipa docker. 
So before I run the container, the dns 10.9.70.3 is down.
When the container runs, the port 53 is bound to the host, so that the docker host (10.9.70.3) becomes a DNS server. 
Then I can re-enable the 10.9.70.3 dns in /etc/resolv.conf

My goal is simple: I want to deploy a freeipa server on my server, using your docker, and in such a way that my server appears to be the freeipa server.

Thanks for your help !

**Comment by adelton** [comment]
If you have `nameserver 10.9.70.3` in your host's `/etc/resolv.conf` as the first line when you first run the container when there is yet no DNS server configured on that IP address, that value will be used as the forwarder value for the setup, that's why you'll see the `Forwarder 10.9.70.3 does not respond` message.

I wouldn't call it "messing up with host setup" when you put the 10.9.70.3 IP address (or 127.0.0.1) to `/etc/resolv.conf` only once the DNS server has actually been setup on that location and not before.

The container will always try to use some decent default value for the forwarder, namely the first line from host's `resolv.conf`. If you just run with `nameserver 212.121.128.10` as the first line, that will be configured as forwarder in bind's configuration.

If you need to force different forwarder value, like that 8.8.8.8, use `-e FORWARDER=8.8.8.8`, or put `nameserver 8.8.8.8` as the first nameserver line in the `resolv.conf`, for the initial FreeIPA container run. Note that I've still not completely sure that this approach is the best for the forwarder configuration, that's why the `FORWARDER` environment variable approach is not documented at this point and might be removed in the future.

**Comment by kforner** [comment]
>I wouldn't call it "messing up with host setup" when you put the 10.9.70.3 IP address (or 127.0.0.1) to >/etc/resolv.conf only once the DNS server has actually been setup on that location and not before.

The problem is that you can not easily restart the freeipa container/service if it is down. 
You have to setup a proces: first remove dns, start or restart freeipa, restore dns

> If you need to force different forwarder value, like that 8.8.8.8, use -e FORWARDER=8.8.8.8

that seems very interesting, I'll test this ASAP. Thanks again.

**Comment by adelton** [comment]
> The problem is that you can not easily restart the freeipa container/service if it is down.

Can you elaborate? What prevents you from just starting it / running new container?

> You have to setup a proces: first remove dns, start or restart freeipa, restore dns

The FreeIPA container internally uses 127.0.0.1 in its `resolv.conf`. Only during the initial, setup stage, the values from host's `resolv.conf` are used for forwarders. But for restarting the container, you don't need to change the anything, if by "remove dns" you mean removing `nameserver` line from host's `resolv.conf`.

**Comment by kforner** [comment]
> Can you elaborate? What prevents you from just starting it / running new container?

Nothing. You're absolutely right: I must remove the local nameserver from resolv.conf before the initial docker run, but for later restarts apparently there's no need anymore to modify it. Great. 

> If you need to force different forwarder value, like that 8.8.8.8, use -e FORWARDER=8.8.8.8
 
works great !!!! Many thanks !

**Comment by adelton** [comment]
> works great

Good. Can we close this issue as resolved or are there some outstanding concerns that you'd need addressed?

**Comment by kforner** [comment]
sure, close it.
For the record, my current config:
```
	docker run --name freeipa -ti \
	-e IPA_SERVER_IP=10.9.70.3 \
	-e FORWARDER=212.121.128.10 \
	-h ipa.quartzbio.com \
	-e PASSWORD=$PASSWORD_VALUE \
	-v /secure/freeipa_server/freeipa/data:/data \
	-v /etc/localtime:/etc/localtime:ro \
	-p 53:53  -p 53:53/udp \
	-p 9980:80 -p 9943:443 \
	-p 389:389 -p 636:636 -p 88:88 -p 464:464 \
	-p 88:88/udp -p 464:464/udp -p 7389:7389 \
	-p 9443:9443 -p 9444:9444 -p 9445:9445  adelton/freeipa-server
```
