### ISSUE TITLE
how to get ipa web app certificate and key ? 

### ISSUE THREAD

**Issue by kforner** [adelton/docker-freeipa#32]
I'd like to get the certificate and private key used by the freeipa web app.

I had to reverse-proxy this web app because it is bound on a non standard port, 9943.
So I setup a virtual host that reverses-proxy the freeipa web app, both on http and https.
For https, apparently there is no way to only forward the https queries to port 9943, without setting a SSL engine.  
So when a client requests a https://ipa.example.test, it gets a response encrypted by the vhost certificate.

I think that causes a problem with the ipa-client-install, (because my proxy certificate is self-signed).
```
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/ipa/ca.crt
  CApath: none
* Server certificate:
* 	subject: xxxxxxxxxxxxxxxxxx
* 	start date: Jul 09 09:45:31 2015 GMT
* 	expire date: Jul 06 09:45:31 2025 GMT
* 	common name: ipa.example.test
* 	issuer: xxxxxxxxxxxxxxxxxxxxxxxx
* NSS error -8172 (SEC_ERROR_UNTRUSTED_ISSUER)
* Peer's certificate issuer has been marked as not trusted by the user.
* Closing connection 0
libcurl failed to execute the HTTP POST transaction, explaining:  Peer's certificate issuer has been marked as not trusted by the user.
```

So I was thinking to reuse the same certificate and private key for my apache proxy that the ones used for the freeipa web ui, but I can't find them.

Does it make sense ?

Regards,
Karl

**Comment by adelton** [comment]
> So I was thinking to reuse the same certificate and private key for my apache proxy that the ones used for the freeipa web ui, but I can't find them.

They should be in the nss database on the FreeIPA machine (in the FreeIPA container). Use `docker exec` to get to the container and extract them there.

**Comment by kforner** [comment]
It worked ! Now the ipa-client-install runs smoothly. 
I used the nss database in /data/etc/httpd/alias/
```
certutil -L -d . -a -n 'Server-Cert' > server.crt 

pk12util -o key.p12 -n 'Server-Cert' -d .
# type the content of pwdfile.txt, then twice ENTER
openssl pkcs12 -in key.p12 -out server.key -nodes
```

**Comment by technologynongmin** [comment]
I have the same trouble. I use the freeipa-server run by docker, and use nginx agent externally.

**Comment by adelton** [comment]
With the latest versions of FreeIPA which uses `mod_ssl` instead of `mod_nss`, the certificate and key are in `/data/var/lib/ipa/certs/httpd.crt` and `/data/var/lib/ipa/private/httpd.key`.

**Comment by technologynongmin** [comment]
My domain name was previously issued with a set of certificates, not X509. How can I use this set of generated certificates in docker?

**Comment by technologynongmin** [comment]
> With the latest versions of FreeIPA which uses `mod_ssl` instead of `mod_nss`, the certificate and key are in `/data/var/lib/ipa/certs/httpd.crt` and `/data/var/lib/ipa/private/httpd.key`.
Nginx configuration certificate requires PEM password @adelton

**Comment by adelton** [comment]
So what are they when not X.509?

You might be able to just copy them to the above mentioned locations in your container.

But it's possible that it will break your setup as they won't be recognied as issued by the FreeIPA's CA.

How would you set things up in FreeIPA outside of containers / docker? Is the situation even container specific? If it's not, I'd suggest setting things up outside of containers first, and potentially seek help in the FreeIPA mailing lists.

If the situation is container specific, please file separate issue, since it does not seem to be as much related to the (closed) one where we are discussing it right now. Exact description of what your are trying to do will be needed in that case. By the way, aren't you trying to do https://www.adelton.com/freeipa/freeipa-behind-ssl-proxy?
