### ISSUE TITLE
use real systemd

### ISSUE THREAD

**Issue by maci0** [adelton/docker-freeipa#6]
Is there anything against using real systemd instead of your replacement ?
I have a working setup here: https://github.com/maci0/docker-systemd-unpriv

**Comment by adelton** [comment]
No, nothing against that. It's actually my long-term plan. There are some changes coming to the EL images WRT systemd so I'd prefer for them to land and use that as a basis for the work.

**Comment by maci0** [comment]
I have  freeipa-server and freeipa-client based on my systemd-unpriv container working here as well. It requires almost no custom code.
I think the most crucial part you implemented is the volume-test stuff. Might look into porting that to my solution as well, was it complete or did it still lack some stuff?

Do you think it is applicable to split up IPA into its components and have a docker container for each ?

**Comment by adelton** [comment]
> I have freeipa-server and freeipa-client based on my systemd-unpriv container working here as well. It requires almost no custom code.

I'll be happy to take a look / review pull request.

> I think the most crucial part you implemented is the volume-test stuff. Might look into porting that to my solution as well, was it complete or did it still lack some stuff?

The main reason why I did not push the volume-based approach as the main branches is, we need to get the upgrades fleshed out. With containers, it's easy to create IPA 3.3 image and start it and have the volume populated with 3.3 data and configuration, and then create 4.0 or 4.1 image and run new container, with the new code and old data. That's actually what I'm looking into right now.

> Do you think it is applicable to split up IPA into its components and have a docker container for each ?

Container is basically separate machine from other service's point of view. Unless the other components know that their peers might not be on the same host (often Unix socket away) and get to assume they can be remote, it's likely to be hard to do. Also, the ipa-server-install and other utilities expect all configured components to be on the same host, which in case of containers means in the same container.

Many of the components also share configuration (like Kerberos client libraries) which would need to be solved somehow. That's why I did not attempt to do any splitting. It might be a useful thing to do and it might better fit the container paradigm but the effort should not be container-specific -- it should be about "make it possible for dirsrv (or other component X) to run on separate host and have that separate host configurable and have the rest of the system understand that configuration", not "move dirsrv (or other component X) to separate container". If you do the first, you will get the second for free. If you do the second, you will likely need to redo a lot of the work that went into the installer code.

**Comment by maci0** [comment]
@adelton 

i just pushed my implemetation up here: https://github.com/maci0/docker-freeipa-server https://github.com/maci0/docker-freeipa-client
its nowhere near as complete as yours. lots of stuff is still hardcoded. but it demonstrates how easy it can be :)

**Comment by adelton** [comment]
Thanks, I will take a look.

**Comment by maci0** [comment]
how do the official RPM packages handle version upgrades ?
I suppose there is some post upgrade script which updates the database etc. Not sure if it would handle downgrades as well.

**Comment by adelton** [comment]
> I suppose there is some post upgrade script which updates the database etc.

Right. But with containers, you do not run the rpm -U operation. Yes, I'm actually looking at the rpm scriptlets to run them.

**Comment by maci0** [comment]
it doesnt seem to do a let except of running 
```
/usr/sbin/ipa-ldap-updater --upgrade --quiet >/dev/null || :
/usr/sbin/ipa-upgradeconfig --quiet >/dev/null || :```
and stopping ipa_kpasswd.service before
im not sure if it is applicable to simply run those commands every time and hope they know that the data doesnt need to be updates

**Comment by adelton** [comment]
The latest master and derived branches now support volumes, and with that upgrades to newer IPA versions. You might want to test that.

As for native systemd/systemd-container, I'm hitting multiple issues when attempting to use it across various OS versions (for example https://bugzilla.redhat.com/show_bug.cgi?id=1201657), so it is not a high priority at the moment.

I'm leaving this issue open for now.

**Comment by adelton** [comment]
Please check the master-systemd branch. It container systemd-based installation.

**Comment by adelton** [comment]
The systemd-based setup is now in master.
