### ISSUE TITLE
For file list fails if no file matches blob.

### ISSUE THREAD

**Issue by iconoeugen** [adelton/docker-freeipa#63]
If the blob expression is not matching and file the for loop will do a single
iteration with the blob expression as value:

```
# for i in /usr/lib/systemd/system/*-dummy.service ; do echo $i ; done
/usr/lib/systemd/system/*-dummy.service
```

This behaviour will lead to errors like:

```
sed: can't read /usr/lib/systemd/system/*-domainname.service: No such file or directory
```

**Comment by adelton** [comment]
Fair point about the use of glob.

But I wonder: what base image and branch do you use that neither of the ```*-domainname.service``` files exists? The Dockerfile is intentionally written in such a way that it should match a particular underlying OS fairly closely, to uncover in build time any changes that might have happened in the repos that we really have no control off.

In this case it's actually less strict than it should be (we likely want ```fedora-domainname.service``` for Fedora and ```rhel-domainname.service``` for RHEL), so my preferred course of action would be to make it stricter, rather than optional (as proposed in https://github.com/adelton/docker-freeipa/pull/64).

**Comment by adelton** [comment]
Closing per explanation above.
