### ISSUE TITLE
docker compose example

### ISSUE THREAD

**Issue by typekpb** [adelton/docker-freeipa#80]
it would be nice to have sample with minimal `docker-compose.yml` client server setup, demonstrating simple kerberos/ldap/... connection from client side.

**Comment by adelton** [comment]
Not a minimal one, it's meant to be fairly complex, but one that hopefully you will find useful: https://github.com/adelton/webauthinfra

**Comment by typekpb** [comment]
thanks!

**Comment by CodingSpiderFox** [comment]
@typekpb did you manage to export the ports so that you can access the freeIP web UI from the host machine?

**Comment by typekpb** [comment]
Nope, gave up

**Comment by vfontanella** [comment]
Hi,
I tried this for awhile now and no luck as well.
Not sure what is going on. It seems the server doesn't start when using docker-compose file.
I'm using docker run successfully, but I will try it again later. Will not give it up so easy.
Thanks for 
Cheer,

**Comment by adelton** [comment]
Are there any specific issues and errors that need to be solved/reviewed?

**Comment by herrfeder** [comment]
Although, it's closed and very old. I found potentially the root cause. 
`docker-compose up` - context will ignore  ENTRYPOINT that are not defined on the last line of the Dockerfile. It seems `docker run` - context will notice ENTRYPOINT everywhere in the Dockerfile. You can bash into the container and will see that the docker-compose container won't run in the right environment with systemd as the root process. Therefore two potential solutions:

  - Put the `ENTRYPOINT ["/usr/local/sbin/init"]` at the end of the Dockerfile
  
OR

  - override the entrypoint in the docker-compose.yml by adding `entrypoint:  ["/usr/local/sbin/init"]`

Despite the age of this Issue, I hope it will help someone.
